version: 2

release:
  draft: false
  use_existing_draft: true

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm64
  main: ./cmd/ssssg

checksum:
  name_template: "checksums.txt"
