global:
  layout: "_layout.html"
  data:
    site_name: "My Site"
    author: "Your Name"

pages:
  - template: "index.html"
    output: "index.html"
    data:
      title: "Home"
      greeting: "Welcome to My Site!"

  - template: "about.html"
    output: "about.html"
    data:
      title: "About"

  - template: "contact.html"
    output: "contact.html"
    data:
      title: "Contact"
